version: '3.8'

services:
  usdy-substreams:
    build: .
    environment:
      - SUBSTREAMS_API_TOKEN=${SUBSTREAMS_API_TOKEN}
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    networks:
      - usdy-network

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=usdy_solana
      - POSTGRES_USER=usdy_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - usdy-network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - usdy-network

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - usdy-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      - CLICKHOUSE_DB=usdy_solana
      - CLICKHOUSE_USER=usdy_user
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-your_password}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - usdy-network

volumes:
  postgres_data:
  grafana_data:
  prometheus_data:
  clickhouse_data:

networks:
  usdy-network:
    driver: bridge
